optimizer: Adam 
amsgrad: 1   #for adam optim



#model-related
model:
  nb_samp: 64600
  first_conv: 1024   # no. of filter coefficients 
  in_channels: 1
  filts: [20, [20, 20], [20, 128], [128, 128]] # no. of filters channel in residual blocks
  blocks: [2, 4]
  nb_fc_node: 1088 # equal to teacher size (1024 rawnet2 + 64 bio)
  gru_node: 1024
  nb_gru_layer: 1
  nb_classes: 2
  is_light: True
  
  



